name: デプロイ(windows zip)

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_for_windows:
    name: Windows用ビルド
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Flutter version from .fvmrc
        run:  echo "FLUTTER_FVM_VERSION=$(jq -r .flutter .fvmrc)" >> $env:GITHUB_ENV

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_FVM_VERSION }}
          cache: true

      - name: Flutter pub get
        run: |
          git config --system core.longpaths true
          flutter pub get

      - name: Get App Version
        run:  |
          echo "version=$(flutter pub run cider version)" >> $env:GITHUB_ENV
          echo "builddir=$(pwd)" >> $env:GITHUB_ENV

      - name: Build for Windows
        run: |
          flutter build windows --release

      - name: Compress files
        run: |
          ren build\windows\x64\runner\Release flutter_test
          Compress-Archive -Path build\windows\x64\runner\flutter_test -DestinationPath flutter_test_${env:version}_windows-x64.zip -Force

      - name: Create tag and release note
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v${env:version} --clobber flutter_test_${env:version}_windows-x64.zip